In [150]:
import os
import pickle
import plotly.io as pio
pio.renderers.default = "notebook_connected"
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [117]:
# from google.colab import drive
# drive.mount('/content/drive')

In [118]:
# Charger les données

data_path = "../data/processed"
file_name = 'dataset_final.pkl'
with open(os.path.join(data_path, file_name), 'rb') as f:
    df = pickle.load(f)

In [119]:
# Charger un seul embedding

embeddings_path = "../data/embeddings"
# file_name = 'emb_sbert_multi.pkl'

# with open(os.path.join(embeddings_path, file_name), 'rb') as f:
#     embedding = pickle.load(f)

In [120]:
# Charger tous les embeddings

# embeddings_path = "../data/embeddings"
# embeddings = {}

# for file_name in os.listdir(embeddings_path):
#     with open(os.path.join(embeddings_path, file_name), 'rb') as f:
#         emb_name = file_name.split('.')[0]
#         embeddings[emb_name] = pickle.load(f)

### BERTopic

In [233]:
from bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.corpus import stopwords
from hdbscan import HDBSCAN

In [122]:
sentences = df["clean_comment"].tolist()

file_name_mutli = 'emb_sbert_multi.pkl'
with open(os.path.join(embeddings_path, file_name_mutli), 'rb') as f:
    embedding_multi = pickle.load(f)

file_name_fr = 'emb_sbert_fr.pkl'
with open(os.path.join(embeddings_path, file_name_fr), 'rb') as f:
    embedding_fr = pickle.load(f)

file_name_perf = 'emb_sbert_multi2.pkl'
with open(os.path.join(embeddings_path, file_name_fr), 'rb') as f:
    embedding_multi2 = pickle.load(f)

In [123]:
print(len(sentences))
print(embedding_multi.shape)
print(embedding_fr.shape)
print(embedding_multi2.shape)

15077
(15077, 384)
(15077, 768)
(15077, 768)

In [238]:
product_words = ['montre', 'montres', 'boucle', 'boucles', 'oreilles', 'oreille', 'paire', 'paires', 'lunettes', 'bracelet', 'bracelets', 'collier', 'iphone', 'téléphone', 'pendentif', 'robot', 'robots', 'aspirateur', 'baskets', 'basket', 'chaussure', 'chaussures', 'sandales', 'plantes', 'plante', 'arbres', 'arbre', 'bulbes', 'willemse', 'sommiers', 'jardin', 'bague', 'lampe', 'lampes', 'abat-jour', 'abat jour', 'lampadaire', 'parfum', 'shampoing', 'shampooing', 'shampooings', 'cheveux', 'masque', 'masques', 'crème', 'élastiques', 'manteau', 'bougie', 'cadre', 'écouteurs', 'vélo', 'robe', 'vêtements', 'bijoux', 'sac', 'portable', 'clio', 'luminaire', 'oreillette', 'induction', 'écouteur', 'couette', 'samsung', 'téléphones', 'smartcase', 'abat', 'apple', 'watch', 'shirt', 'tee', 'chemise', 'shirts', 'hortensias', 'orchidée', 'sacs', 'plant', 'reconditionné']

models = {}

for embedding, name in zip([embedding_fr, embedding_multi, embedding_multi2], ["français", "multilingue", "multilingue_2"]):

    vectorizer_model = CountVectorizer(
        stop_words=stopwords.words("french") + product_words,
        ngram_range=(1, 3),
        #min_df=2,
        max_df=0.95
    )
    # ctfidf_model = ClassTfidfTransformer()

    hdbscan_model = HDBSCAN(
    min_cluster_size=10,
    min_samples=3
    )
    
    topic_model = BERTopic(
        language="french",
        vectorizer_model=vectorizer_model,
        hdbscan_model=hdbscan_model,
        verbose=False,
        nr_topics="auto"
        # ctfidf_model=ctfidf_model
    )
    
    topics, probs = topic_model.fit_transform(sentences, embedding)

    topic_model.reduce_topics(sentences, nr_topics=30)

    models[name] = topic_model

### Evaluation

#### Diversité

In [239]:
from itertools import chain

def topic_diversity(topic_model, top_n=10):
    """
    Calcule la diversité des topics d'un modèle BERTopic.
    """
    topics = topic_model.get_topics()

    # On extrait les mots uniquement (sans les scores)
    topic_words = []
    for topic_id, word_scores in topics.items():
        # BERTopic place les topics -1 et autres meta-topics, donc on ignore topic -1
        if topic_id == -1:
            continue
        top_words = [w for (w, score) in word_scores[:top_n]]
        topic_words.append(top_words)

    # Liste aplatie
    all_words = list(chain.from_iterable(topic_words))
    unique_words = set(all_words)

    return len(unique_words) / len(all_words)


# Calcul du score pour chaque modèle
diversity_scores = {}

for name, model in models.items():
    score = topic_diversity(model, top_n=10)
    diversity_scores[name] = score

diversity_scores

{'français': 0.6448275862068965,
 'multilingue': 0.7344827586206897,
 'multilingue_2': 0.7862068965517242}

#### Score de cohérence

In [240]:
from gensim.models import CoherenceModel
from gensim.corpora import Dictionary

os.environ["TOKENIZERS_PARALLELISM"] = "false"

def coherence_score(topic_model, documents, top_n=10):
    """
    Calcule le score de cohérence classique c_v pour un modèle BERTopic.
    """
    # print(type(model.get_topics()))
    # print(model.get_topics()[0])
    # Récupère les topics (liste de mots par topic)
    topics = topic_model.get_topics()
    topic_words = []
    for topic_id, word_scores in topics.items():
        if topic_id == -1:
            continue
        words = []
        for w, s in word_scores[:top_n]:
            w = str(w)
            words.append(w)
        topic_words.append(words)
    # print(topic_words[:3])

    # Préparer le corpus pour Gensim
    tokenized_docs = [doc.lower().split() for doc in documents]  # tokenisation simple
    dictionary = Dictionary(tokenized_docs)
    corpus = [dictionary.doc2bow(text) for text in tokenized_docs]

    # Calcul du score
    cm = CoherenceModel(
        topics=topic_words,
        texts=tokenized_docs,
        dictionary=dictionary,
        coherence='c_v'
    )
    
    return cm.get_coherence()

# Exemple
for name, model in models.items():
    score = coherence_score(model, sentences, top_n=10)
    print(f"{name} - Coherence c_v: {score:.4f}")

# score = coherence_score(models["multilingue_2"], sentences, top_n=10)
# print(f"{name} - Coherence c_v: {score:.4f}")

français - Coherence c_v: 0.5387
multilingue - Coherence c_v: 0.4318
multilingue_2 - Coherence c_v: 0.6073

#### Embedding-based coherence score

In [242]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def embedding_coherence(topic_model, embedder, top_n=10):
    """
    Calcule la cohérence basée sur les embeddings pour un modèle BERTopic.
    embedder : modèle sentence-transformers pour transformer les mots en vecteurs.
    """
    topics = topic_model.get_topics()
    scores = []

    for topic_id, word_scores in topics.items():
        if topic_id == -1:
            continue
        top_words = [w for w, _ in word_scores[:top_n]]
        word_embeddings = embedder.encode(top_words)
        sim_matrix = cosine_similarity(word_embeddings)
        
        # On enlève la diagonale (sim = 1)
        n = len(top_words)
        if n > 1:
            sims = (sim_matrix.sum() - n) / (n*(n-1))  # moyenne des cosinus
            scores.append(sims)

    return np.mean(scores)

# Exemple avec un modèle SentenceTransformer
from sentence_transformers import SentenceTransformer
embedder = SentenceTransformer('all-MiniLM-L6-v2')

for name, model in models.items():
    score = embedding_coherence(model, embedder, top_n=10)
    print(f"{name} - Embedding-based coherence: {score:.4f}")

français - Embedding-based coherence: 0.3950
multilingue - Embedding-based coherence: 0.3404
multilingue_2 - Embedding-based coherence: 0.4360

In [246]:
for name, model in models.items():
    with open(f"../models/topic_modeling/bertopic_{name}.pkl", "wb") as f:
        pickle.dump(model, f)

### Visualisation

In [8]:
# CHARGER LES MODELES ENREGISTRES
# models = {}
# for name in ["français", "multilingue", "multilingue_2"]:
#     with open(os.path.join("../models/topic_modeling/", f"bertopic_{name}.pkl"), 'rb') as f:
#         models[name] = pickle.load(f)

In [247]:
all_topics_words = {}
topic_model = models["multilingue_2"]

for topic_id in topic_model.get_topics().keys():
    if topic_id == -1:
        continue  # ignorer les outliers
    all_topics_words[topic_id] = [word for word, _ in topic_model.get_topic(topic_id)]

all_topics_words

{0: ['commande',
  'plus',
  'livraison',
  'colis',
  'site',
  'service',
  'vente',
  'client',
  'bien',
  'remboursement'],
 1: ['conforme',
  'livraison',
  'description',
  'rapide',
  'attentes',
  'conforme description',
  'produit conforme',
  'conformes',
  'produit',
  'prévue'],
 2: ['conforme',
  'attentes',
  'conforme attentes',
  'description',
  'produit conforme',
  'correspond',
  'attentes produit',
  'produit',
  'conforme description',
  'conforme commande'],
 3: ['rien dire',
  'rien',
  'dire',
  'rien redire',
  'redire',
  'parfait',
  'parfait rien',
  'rien dire rien',
  'dire rien',
  'parfait rien dire'],
 4: ['satisfaite',
  'très satisfaite',
  'contente',
  'achat très',
  'achat',
  'satisfaite achat',
  'achat très satisfaite',
  'très contente',
  'satisfaite achat très',
  'très satisfaite achat'],
 5: ['qualité',
  'déçue',
  'déçue qualité',
  'déçu',
  'photo',
  'déçu qualité',
  'correspondent',
  'articles',
  'photos',
  'correspond'],
 6: ['trop',
  'joli',
  'petit',
  'très joli',
  'trop petit',
  'jolie',
  'super',
  'beau',
  'très jolie',
  'super belle'],
 7: ['rapide',
  'livraison rapide',
  'produit',
  'livraison',
  'qualité',
  'bonne qualité',
  'conforme',
  'qualité livraison rapide',
  'bonne',
  'qualité livraison'],
 8: ['long',
  'trop long',
  'trop',
  'livraison',
  'livraison trop',
  'livraison trop long',
  'long délais',
  'délai',
  'entre commande',
  'long délai'],
 9: ['rien',
  'rien dire',
  'dire',
  'rien redire',
  'redire',
  'signaler',
  'rien dire rien',
  'dire rien',
  'rien signaler',
  'bien rien'],
 10: ['conforme',
  'commande',
  'satisfaite',
  'satisfaite commande',
  'conforme commande',
  'commande satisfaite',
  'commande conforme',
  'commande satisfaite commande',
  'description',
  'conforme photos'],
 11: ['rapport qualité',
  'rapport qualité prix',
  'qualité prix',
  'rapport',
  'bon rapport qualité',
  'bon rapport',
  'prix',
  'qualité',
  'bon',
  'très bon rapport'],
 12: ['comme habitude',
  'ensemble',
  'habitude',
  'bien',
  'bien ensemble',
  'aime',
  'comme',
  'bien aimé',
  'bien ensemble très',
  'aimé'],
 13: ['avant date',
  'date',
  'date prévue',
  'avant date prévue',
  'avant',
  'prévue',
  'arrivé avant date',
  'arrivé avant',
  'prévu',
  'arrivé'],
 14: ['délai',
  'livraison',
  'long',
  'délai livraison',
  'longue',
  'livraison long',
  'trop',
  'trop longue',
  'livraison trop',
  'délais livraison long'],
 15: ['beaux',
  'très beaux',
  'magnifique',
  'beau',
  'articles très beaux',
  'tissus',
  'produits',
  'top',
  'jolis',
  'articles très'],
 16: ['satisfaite',
  'merci',
  'satisfaite merci',
  'très satisfaite',
  'très contente très',
  'contente très',
  'contente très satisfaite',
  'contente',
  'très contente',
  'merci beaucoup'],
 17: ['bonne qualité',
  'qualité',
  'bonne',
  'très bonne qualité',
  'très bonne',
  'bonne qualité produits',
  'bonne qualité produit',
  'qualité produit',
  'qualité produits',
  'bonne qualité très'],
 18: ['conformes',
  'photos',
  'conformes photos',
  'articles',
  'articles conformes',
  'bien',
  'jolis',
  'jolis articles bien',
  'photos tres',
  'belles'],
 19: ['service',
  'service client',
  'client',
  'besoin',
  'client produits défectueux',
  'service client produits',
  'client produits',
  'besoin service client',
  'besoin service',
  'produits défectueux'],
 20: ['satisfaite',
  'livraison très satisfaite',
  'très satisfaite',
  'livraison très',
  'livraison',
  'produit livraison',
  'rapidité',
  'rapidité livraison',
  'satisfaite commande',
  'livraison satisfaite'],
 21: ['passé tout',
  'bien passé tout',
  'bien passé',
  'passé',
  'tout bien',
  'tout bien passé',
  'passé tout bien',
  'tout',
  'bien',
  'très bien passé'],
 22: ['temps',
  'livraison temps',
  'arrivée temps',
  'temps livraison',
  'temps livraison temps',
  'arrivée temps livraison',
  'temps livré',
  'commande arrivée temps',
  'temps produit',
  'livré temps'],
 23: ['recommande',
  'très satisfaite recommande',
  'satisfaite recommande',
  'tres',
  'bon',
  'bon produit',
  'satisfaite',
  'bon service recommandeerai',
  'bien recommande trèsz',
  'assez satisfaisante'],
 24: ['cadeau merci',
  'merci',
  'cadeau',
  'ras',
  'cette commande',
  'cadeau merci showroomprive',
  'cadeau merci cette',
  'cadeau conforme',
  'cadeau merci jolie',
  'cadeau conforme satisfaite'],
 25: ['nul nul',
  'nul',
  'nul nul nul',
  'merci',
  'colissimo',
  'moitié',
  'actuellement enfin',
  'zoé semblant',
  'achat canapé angle',
  'amazon passé commande'],
 26: ['décevant',
  'mauvaise qualité',
  'arrivée incomplete',
  'arrivée incomplete manque',
  'attentes ras comme',
  'aucune notice français',
  'articles normal',
  'article décevant très',
  'camp retour effectué',
  'commande day camp'],
 27: ['photo',
  'comme photo',
  'comme',
  'comme photo ressemble',
  'comme photo comme',
  'beaucoup plus gros',
  'bien comme photos',
  'bonnet trop',
  'bonnet trop grand',
  'bien dommage rendu'],
 28: ['tous points',
  'points',
  'tous',
  'tout point',
  'bien tous points',
  'conforme tous',
  'conforme tous points',
  'points conforme',
  'tous points conforme',
  'tout']}

In [248]:
# topics trouvés
models["français"].get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,4802,-1_livraison_commande_qualité_bien,"[livraison, commande, qualité, bien, produit, ...",[livraison trop longue et produit de mauvaise ...
1,0,7300,0_commande_plus_colis_site,"[commande, plus, colis, site, service, vente, ...",[j'avais déjà écrit un avis sur vente-privée i...
2,1,427,1_article_carton_cassé_peu,"[article, carton, cassé, peu, livraison, manqu...","[il manque un article, il manque un article, i..."
3,2,374,2_livraison_peu_livraison peu_long,"[livraison, peu, livraison peu, long, peu long...","[délai de livraison un peu long, le délai de l..."
4,3,297,3_satisfaite_rapide_parfait_livraison,"[satisfaite, rapide, parfait, livraison, comma...","[satisfaite de ma commande, satisfaite de la c..."
5,4,202,4_rien dire_rien_dire_parfait,"[rien dire, rien, dire, parfait, merci, rien r...","[parfait , rien à dire, parfait rien a dire ....."
6,5,187,5_rapide_livraison_livraison rapide_produit,"[rapide, livraison, livraison rapide, produit,...","[bon produit et livraison rapide, bon produit ..."
7,6,166,6_satisfaite_très satisfaite_contente_commande...,"[satisfaite, très satisfaite, contente, comman...","[très satisfaite de la commande ., très satisf..."
8,7,161,7_satisfaite_très satisfaite_contente_merci,"[satisfaite, très satisfaite, contente, merci,...","[merci je suis très satisfaite, j ai été très ..."
9,8,138,8_qualité_bonne qualité_bonne_belle,"[qualité, bonne qualité, bonne, belle, qualité...","[déçue par la qualité du sac, déçue par la qua..."
10,9,128,9_date_prévue_avant date_date prévue,"[date, prévue, avant date, date prévue, avant,...","[super , arrivé avant la date prévue, arrivée ..."
11,10,123,10_conforme_conforme commande_description_prod...,"[conforme, conforme commande, description, pro...","[conforme a ce que j ai commande, conforme a l..."
12,11,110,11_conforme_description_attentes_livraison,"[conforme, description, attentes, livraison, c...",[produit conforme à la description livraison d...
13,12,82,12_rapport qualité_rapport qualité prix_qualit...,"[rapport qualité, rapport qualité prix, qualit...",[très bon rapport qualité prix et livraison pl...
14,13,74,13_reçu_commande_jamais_rien,"[reçu, commande, jamais, rien, colis, fuir, lo...",[l ’ horreur des conseillers pitoyables ! ! ! ...
15,14,68,14_long_trop long_trop_livraison,"[long, trop long, trop, livraison, livraison t...","[le délai de livraison est trop long, délai de..."
16,15,62,15_attentes_conforme attentes_conforme_attente...,"[attentes, conforme attentes, conforme, attent...","[produit conforme à mes attentes, produit conf..."
17,16,57,16_photo_photos_correspondent_correspond,"[photo, photos, correspondent, correspond, com...",[les vêtements sont exactement comme sur la ph...
18,17,52,17_rapide_livraison rapide_livraison_produit,"[rapide, livraison rapide, livraison, produit,...","[produit conforme et livraison rapide ., parfa..."
19,18,43,18_satisfaite_rien dire_livraison_rien,"[satisfaite, rien dire, livraison, rien, dire,...",[très satisfaite de ma commande et de la rapid...
20,19,41,19_rien_rien dire_dire_rien redire,"[rien, rien dire, dire, rien redire, redire, r...","[parfait rien à dire, rien n ' a dire, je rien..."
21,20,31,20_beaux_très beaux_qualités_produits,"[beaux, très beaux, qualités, produits, très b...",[produits très bonne qualités et les services ...
22,21,27,21_joli_très joli_jolie_beau,"[joli, très joli, jolie, beau, très jolie, sup...","[merci ! très joli tapis !, le bijou est très ..."
23,22,25,22_qualité_bonne qualité_bonne_très bonne qualité,"[qualité, bonne qualité, bonne, très bonne qua...","[vêtements de bonne qualité, sac de bonne qual..."
24,23,21,23_service_service client_client_service clien...,"[service, service client, client, service clie...",[pas besoin de joindre le service client car a...
25,24,21,24_rapport qualité_rapport qualité prix_qualit...,"[rapport qualité, rapport qualité prix, qualit...","[très bon rapport qualité prix, bon rapport qu..."
26,25,20,25_passé tout_bien passé tout_bien passé_passé,"[passé tout, bien passé tout, bien passé, pass...","[tout s'est bien passé, tout s'est bien passé,..."
27,26,16,26_temps_livraison temps_arrivée temps_temps l...,"[temps, livraison temps, arrivée temps, temps ...","[livraison dans les temps !, livraison dans le..."
28,27,12,27_tous points_points_tout point_tous,"[tous points, points, tout point, tous, tout, ...","[commande conforme en tous points, très bien e..."
29,28,10,28_taillent_bottines_peu_pointure,"[taillent, bottines, peu, pointure, leggings, ...","[j ’ ai commandé des bottines , elle taille un..."

In [249]:
# topics trouvés
models["multilingue"].get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,5429,-1_commande_plus_colis_service,"[commande, plus, colis, service, livraison, si...",[voici mon expérience avec vente-privée . depu...
1,0,7498,0_livraison_commande_très_plus,"[livraison, commande, très, plus, site, colis,...",[une petite valise cabine delsey commandée et ...
2,1,449,1_très_plus_commandé_commande,"[très, plus, commandé, commande, pointure, tai...",[en date du 15/05/2020 je commande une paire d...
3,2,276,2_photo_photos_couleur_conforme,"[photo, photos, couleur, conforme, conforme ph...","[produit conforme à la photo, produit pas conf..."
4,3,225,3_très_showroom_service_satisfaite,"[très, showroom, service, satisfaite, showroom...","[très satisfaite du service showroom showroom,..."
5,4,162,4_qualité_produits_déçu_produit,"[qualité, produits, déçu, produit, déçue, très...","[je suis déçue de la qualité, très déçue par l..."
6,5,127,5_or_bagues_avoir_pierre,"[or, bagues, avoir, pierre, très, reçu, plus, ...",[bonjour je vous fais par de mon expérience d ...
7,6,117,6_jours_plus_mois_vente,"[jours, plus, mois, vente, prs, après, batteri...",[j'ai acheté un forfait free mobile avec un té...
8,7,81,7_attentes_conforme attentes_correspond attent...,"[attentes, conforme attentes, correspond atten...","[conforme a mes attentes, conforme à mes atten..."
9,8,77,8_chaises_chaise_fauteuil_plus,"[chaises, chaise, fauteuil, plus, commandé, ve...",[ayant commandé quatres chaises de salle à man...
10,9,70,9_très_reçu_déçu_cassée,"[très, reçu, déçu, cassée, elles, déçue, sans,...",[je suis très déçu pourtant au début il n ' y ...
11,10,62,10_très_balmain_belle_magnifique,"[très, balmain, belle, magnifique, très belle,...","[la commande a été très longue à venir , puis ..."
12,11,61,11_reçu_reçu colis_colis_rien reçu,"[reçu, reçu colis, colis, rien reçu, reçu reçu...","[je n ai pas reçu le colis ! ! ! !, je n ’ ai ..."
13,12,56,12_cadeau_merci_très_signe,"[cadeau, merci, très, signe, belle, fidélité, ...","[merci beaucoup pour ce cadeau, merci pour le ..."
14,13,38,13_coton_qualité_tissus_trop,"[coton, qualité, tissus, trop, polyester, meub...",[la bâche est difficile à ajuster . les scratc...
15,14,33,14_odeur_produit_très_produits,"[odeur, produit, très, produits, soin, faire s...",[j'ai été très déçue par un des produits `` hu...
16,15,32,15_service client_client_service_besoin,"[service client, client, service, besoin, beso...",[je n'ai pas eu de contact avec le service cli...
17,16,32,16_adore_cette marque_adoré_aimé,"[adore, cette marque, adoré, aimé, marque, ado...","[super produit j'adore cette marque, j'adore c..."
18,17,31,17_frais_amazon_port_frais port,"[frais, amazon, port, frais port, plus, livrai...",[des produits de qualité mais leur prix n'est ...
19,18,30,18_toujours_prix_après_plus,"[toujours, prix, après, plus, fournisseur, rem...","[bonjour , j'ai renvoyé à showroomprivé un rob..."
20,19,28,19_habitude_comme habitude_temps_comme,"[habitude, comme habitude, temps, comme, livré...","[comme d ’ habitude au top, super comme d ’ ha..."
21,20,27,20_nickel_tout nickel_nickel rien_rien,"[nickel, tout nickel, nickel rien, rien, produ...","[ras nickel rien à dire, ras tout était nickel..."
22,21,24,21_description_conforme description_conforme_d...,"[description, conforme description, conforme, ...","[produit conforme à la description, conforme a..."
23,22,24,22_verre_cassé_arrivé_verre cassé,"[verre, cassé, arrivé, verre cassé, verres, ar...",[il y avait un verre cassé dans mon colis je s...
24,23,22,23_jai_taille_pire_commande,"[jai, taille, pire, commande, reçu, très, joli...",[jai acheté des baskets sans savoir que c etai...
25,24,15,24_arrivées_vente_vente privée_privée,"[arrivées, vente, vente privée, privée, appelé...","[cliente depuis 2009 , j'ai tenté pour la 1ère..."
26,25,15,25_confortable_confortable très_lit_jaune,"[confortable, confortable très, lit, jaune, co...","[au top , mes bottines sont vraiment splendide..."
27,26,13,26_toujours_entreprise_sans_vente privée,"[toujours, entreprise, sans, vente privée, pri...",[entreprise incompétente j'ai commandé un vélo...
28,27,12,27_boites_prise_abîmé_écrit anomalie ça,"[boites, prise, abîmé, écrit anomalie ça, abîm...",[livraison dans les temps . le produit n'était...
29,28,11,28_moyenne_qualité moyenne_qualité_moyenne qua...,"[moyenne, qualité moyenne, qualité, moyenne qu...",[la qualité est moyenne surtout au niveau des ...

In [250]:
# topics trouvés
models["multilingue_2"].get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,4875,-1_livraison_commande_qualité_plus,"[livraison, commande, qualité, plus, produit, ...",[déçu par la qualité des lunettes et livraison...
1,0,8843,0_commande_plus_livraison_colis,"[commande, plus, livraison, colis, site, servi...","[premier et dernier achat de chez eux , plus j..."
2,1,179,1_conforme_livraison_description_rapide,"[conforme, livraison, description, rapide, att...","[livraison rapide , produit conforme à mes att..."
3,2,172,2_conforme_attentes_conforme attentes_description,"[conforme, attentes, conforme attentes, descri...","[conforme a mes attentes, conforme à mes atten..."
4,3,139,3_rien dire_rien_dire_rien redire,"[rien dire, rien, dire, rien redire, redire, p...","[parfait rien a dire ..., parfait , rien a dir..."
5,4,99,4_satisfaite_très satisfaite_contente_achat très,"[satisfaite, très satisfaite, contente, achat ...","[très satisfaite de mon achat ., je suis très ..."
6,5,92,5_qualité_déçue_déçue qualité_déçu,"[qualité, déçue, déçue qualité, déçu, photo, d...","[déçue par la qualité des vêtements, je suis d..."
7,6,61,6_trop_joli_petit_très joli,"[trop, joli, petit, très joli, trop petit, jol...","[les articles étaient beaucoup trop petit ., t..."
8,7,56,7_rapide_livraison rapide_produit_livraison,"[rapide, livraison rapide, produit, livraison,...",[article de très bonne qualité et livraison ra...
9,8,54,8_long_trop long_trop_livraison,"[long, trop long, trop, livraison, livraison t...","[délai de livraison trop long, le délai de liv..."
10,9,52,9_rien_rien dire_dire_rien redire,"[rien, rien dire, dire, rien redire, redire, s...","[parfait rien à dire, rien n ' a dire, je rien..."
11,10,48,10_conforme_commande_satisfaite_satisfaite com...,"[conforme, commande, satisfaite, satisfaite co...","[conforme à la commande, conforme a la command..."
12,11,45,11_rapport qualité_rapport qualité prix_qualit...,"[rapport qualité, rapport qualité prix, qualit...","[très bon rapport qualité prix, bon rapport qu..."
13,12,41,12_comme habitude_ensemble_habitude_bien,"[comme habitude, ensemble, habitude, bien, bie...","[très bien dans l ’ ensemble, très bien dans l..."
14,13,34,13_avant date_date_date prévue_avant date prévue,"[avant date, date, date prévue, avant date pré...","[parfait arrivé avant la date prévue, arrivé a..."
15,14,31,14_délai_livraison_long_délai livraison,"[délai, livraison, long, délai livraison, long...","[délai de livraison respecté, délai de livrais..."
16,15,30,15_beaux_très beaux_magnifique_beau,"[beaux, très beaux, magnifique, beau, articles...",[marque découverte grâce à showroom : tissus a...
17,16,27,16_satisfaite_merci_satisfaite merci_très sati...,"[satisfaite, merci, satisfaite merci, très sat...","[je suis satisfaite , merci, je suis très sati..."
18,17,25,17_bonne qualité_qualité_bonne_très bonne qualité,"[bonne qualité, qualité, bonne, très bonne qua...","[sac de bonne qualité, vêtements de bonne qual..."
19,18,23,18_conformes_photos_conformes photos_articles,"[conformes, photos, conformes photos, articles...","[beaux bijoux , conformes aux photos et emball..."
20,19,22,19_service_service client_client_besoin,"[service, service client, client, besoin, clie...",[pas besoin de joindre le service client car a...
21,20,22,20_satisfaite_livraison très satisfaite_très s...,"[satisfaite, livraison très satisfaite, très s...",[très satisfaite du produit et de la livraison...
22,21,20,21_passé tout_bien passé tout_bien passé_passé,"[passé tout, bien passé tout, bien passé, pass...","[tout s'est bien passé, tout c ’ est bien pass..."
23,22,18,22_temps_livraison temps_arrivée temps_temps l...,"[temps, livraison temps, arrivée temps, temps ...","[livraison dans les temps, livraison dans les ..."
24,23,13,23_recommande_très satisfaite recommande_satis...,"[recommande, très satisfaite recommande, satis...","[expérience assez satisfaisante je recommande,..."
25,24,12,24_cadeau merci_merci_cadeau_ras,"[cadeau merci, merci, cadeau, ras, cette comma...","[merci beaucoup pour ce cadeau, merci à showro..."
26,25,11,25_nul nul_nul_nul nul nul_merci,"[nul nul, nul, nul nul nul, merci, colissimo, ...","[livraison plus rapide que prévue , colis arri..."
27,26,11,26_décevant_mauvaise qualité_arrivée incomplet...,"[décevant, mauvaise qualité, arrivée incomplet...",[qualité moyenne ... aucune notice en français...
28,27,11,27_photo_comme photo_comme_comme photo ressemble,"[photo, comme photo, comme, comme photo ressem...","[pas du tout comme sur la photo, bonnet trop g..."
29,28,11,28_tous points_points_tous_tout point,"[tous points, points, tous, tout point, bien t...","[commande conforme en tous points, très bien e..."

In [251]:
# Mots-clés associés à un topic
models["français"].get_topic(0)

[('commande', np.float64(0.010340701984429202)),
 ('plus', np.float64(0.00986959838147149)),
 ('colis', np.float64(0.007717754654670451)),
 ('site', np.float64(0.007657288166145758)),
 ('service', np.float64(0.007449170381609198)),
 ('vente', np.float64(0.0067841269904930415)),
 ('livraison', np.float64(0.00670084095999104)),
 ('client', np.float64(0.00665961608731454)),
 ('remboursement', np.float64(0.0059745462739572855)),
 ('après', np.float64(0.005613513495396216))]

In [252]:
# Mots-clés associés à un topic
models["multilingue"].get_topic(0)

[('livraison', np.float64(0.01209649178161709)),
 ('commande', np.float64(0.01157781764070824)),
 ('très', np.float64(0.011430530478093958)),
 ('plus', np.float64(0.00938488756488948)),
 ('site', np.float64(0.007777954416698765)),
 ('colis', np.float64(0.007690737782841499)),
 ('bien', np.float64(0.007397506768599091)),
 ('service', np.float64(0.006689339871293234)),
 ('tout', np.float64(0.006139802726551881)),
 ('qualité', np.float64(0.006094333420782947))]

In [253]:
fig1 = models["français"].visualize_topics(top_n_topics=10)
fig2 = models["multilingue"].visualize_topics(top_n_topics=10)

combined_fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=("Modèle 1 : Français", "Modèle 2 : Multilingue")
)

for trace in fig1['data']:
    combined_fig.add_trace(trace, row=1, col=1)

for trace in fig2['data']:
    combined_fig.add_trace(trace, row=1, col=2)

combined_fig.update_layout(
    title_text="Répartition des topics",
    showlegend=False,
    height=600,
    width=1000
)

combined_fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [ ]:
models["français"].visualize_barchart(top_n_topics=10)

In [ ]:
models["multilingue"].visualize_barchart(top_n_topics=10)

In [ ]:
models["multilingue"].visualize_hierarchy()

In [ ]:
models["multilingue"].visualize_hierarchy()