In [1]:
import os
import pickle
import plotly.io as pio
pio.renderers.default = "notebook_connected"
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

In [3]:
# Charger les données

data_path = "../data/processed"
file_name = 'dataset_final.pkl'
with open(os.path.join(data_path, file_name), 'rb') as f:
    df = pickle.load(f)

In [4]:
# Charger un seul embedding

embeddings_path = "../data/embeddings"
# file_name = 'emb_sbert_multi.pkl'

# with open(os.path.join(embeddings_path, file_name), 'rb') as f:
#     embedding = pickle.load(f)

In [5]:
# Charger tous les embeddings

# embeddings_path = "../data/embeddings"
# embeddings = {}

# for file_name in os.listdir(embeddings_path):
#     with open(os.path.join(embeddings_path, file_name), 'rb') as f:
#         emb_name = file_name.split('.')[0]
#         embeddings[emb_name] = pickle.load(f)

### BERTopic

In [6]:
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.corpus import stopwords

/mnt/c/Users/charb/Documents/ALTERNANCE/Datascientest/Projet/TrustPilot/DS/trustpilot/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning:

IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

In [22]:
sentences = df["clean_comment"].tolist()

file_name_mutli = 'emb_sbert_multi.pkl'
with open(os.path.join(embeddings_path, file_name_mutli), 'rb') as f:
    embedding_multi = pickle.load(f)

file_name_fr = 'emb_sbert_fr.pkl'
with open(os.path.join(embeddings_path, file_name_fr), 'rb') as f:
    embedding_fr = pickle.load(f)

In [23]:
models = {}

for embedding, name in zip([embedding_multi, embedding_fr], ["multilingue", "français"]):

    vectorizer_model = CountVectorizer(
        stop_words=stopwords.words("french"),
        ngram_range=(1, 2),
        min_df=5
    )
    
    topic_model = BERTopic(
        language="french",
        vectorizer_model=vectorizer_model,
        verbose=True,
        nr_topics="auto"
    )
    
    topics, probs = topic_model.fit_transform(sentences, embedding_multi)

    models[name] = (topic_model)

2025-11-03 18:32:38,417 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-11-03 18:32:40,414 - BERTopic - Dimensionality - Completed ✓
2025-11-03 18:32:40,416 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-11-03 18:32:40,781 - BERTopic - Cluster - Completed ✓
2025-11-03 18:32:40,782 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-11-03 18:32:41,459 - BERTopic - Representation - Completed ✓
2025-11-03 18:32:41,460 - BERTopic - Topic reduction - Reducing number of topics
2025-11-03 18:32:41,496 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-11-03 18:32:42,169 - BERTopic - Representation - Completed ✓
2025-11-03 18:32:42,172 - BERTopic - Topic reduction - Reduced number of topics from 163 to 61
2025-11-03 18:32:42,344 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-11-03 18:32:44,368 - BERTopic - Dimensionality - Completed ✓
2025-11-03 18:32:44,370 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-11-03 18:32:44,776 - BERTopic - Cluster - Completed ✓
2025-11-03 18:32:44,777 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-11-03 18:32:45,454 - BERTopic - Representation - Completed ✓
2025-11-03 18:32:45,455 - BERTopic - Topic reduction - Reducing number of topics
2025-11-03 18:32:45,483 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-11-03 18:32:46,124 - BERTopic - Representation - Completed ✓
2025-11-03 18:32:46,126 - BERTopic - Topic reduction - Reduced number of topics from 144 to 23

In [25]:
# topics trouvés
models["français"].get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,6112,-1_commande_plus_livraison_colis,"[commande, plus, livraison, colis, site, servi...",[très aléatoire : parfois les produits sont tr...
1,0,8198,0_commande_livraison_très_plus,"[commande, livraison, très, plus, colis, bien,...",[j'avais commandé une paire de chaussures il y...
2,1,96,1_montre_site_donc_acheté,"[montre, site, donc, acheté, fonctionne, plus,...","[bonjour , pour une première fois que je comma..."
3,2,89,2_sac_beau_très beau_très,"[sac, beau, très beau, très, joli, bonne quali...",[très beau sac . correspond exactement à la ph...
4,3,63,3_montre_très_magnifique_très belle,"[montre, très, magnifique, très belle, belle, ...",[une très belle montre chic et classe .. juste...
5,4,58,4_produits_produit_peu_très,"[produits, produit, peu, très, contre, plastiq...",[j'ai acheté un lot de produits pour cheveux d...
6,5,57,5_bracelet_bracelets_très_déçue,"[bracelet, bracelets, très, déçue, déçue car, ...",[livraison rapide . et bracelet très jolis au ...
7,6,57,6_téléphone_jours_sav_appareil,"[téléphone, jours, sav, appareil, achat, garan...","[je dois mettre une étoile , mais ça ne les va..."
8,7,46,7_cadeau_merci_signe_très,"[cadeau, merci, signe, très, cadeaux, pendenti...","[merci beaucoup pour ce cadeau, merci pour le ..."
9,8,45,8_boucle_paire_déçue_peu déçue,"[boucle, paire, déçue, peu déçue, peu, cassée,...",[pas du tout satisfaite car une boucle d'oreil...
10,9,31,9_service client_besoin_client_service,"[service client, besoin, client, service, cont...","[pas eu besoin de contacter le service client,..."
11,10,30,10_taille_paire_jai_retour,"[taille, paire, jai, retour, 40, reçu, donc, p...",[escroc ! 09/12/2017 je commande chez ventepri...
12,11,28,11_fournisseur_toujours_prix_après,"[fournisseur, toujours, prix, après, descripti...",[bonjourj'ai commandé un robot à ( 109€ ) et u...
13,12,26,12_rien dire_rien_produit_tout,"[rien dire, rien, produit, tout, magnifiques, ...","[ras nickel rien à dire, rien à dire tout est ..."
14,13,24,13_temps_conforme description_délais_conforme,"[temps, conforme description, délais, conforme...","[arrivé dans les délais estimés , conforme à l..."
15,14,20,14_commande_sans explication_livrée_conforme c...,"[commande, sans explication, livrée, conforme ...","[le commande ne corresponde, la commande n est..."
16,15,17,15_vente_lamentable_appelé_arrivées,"[vente, lamentable, appelé, arrivées, vente pr...","[cliente depuis 2009 , j'ai tenté pour la 1ère..."
17,16,15,16_qualité_100_mauvaise qualité_mauvaise,"[qualité, 100, mauvaise qualité, mauvaise, qua...",[si vous n êtes pas regardant allez y. sinon n...
18,17,14,17_attentes_commande conforme_conforme attente...,"[attentes, commande conforme, conforme attente...","[commande conforme à mes attentes, commande co..."
19,18,14,18_description_conforme description_conforme_c...,"[description, conforme description, conforme, ...","[polo conforme à la description, conforme a la..."
20,19,13,19_cuir_marque_honte_prix,"[cuir, marque, honte, prix, etait, parce, car,...","[prix gonflés , fausse promotion c est une hon..."
21,20,13,20_bague_très belle_belle_jolie,"[bague, très belle, belle, jolie, magnifique, ...","[la bague est magnifique !, reçu la commande t..."
22,21,11,21_description_conforme description_produits c...,"[description, conforme description, produits c...","[marchandise conforme à la description ., prod..."

In [26]:
# topics trouvés
models["multilingue"].get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,6601,-1_commande_plus_livraison_colis,"[commande, plus, livraison, colis, service, si...",[je suis client depuis des année mais ces dern...
1,0,5412,0_commande_livraison_très_plus,"[commande, livraison, très, plus, service, col...",[j'ai effectué 6 achats sur vente privée en 3 ...
2,1,292,1_carton_abîmé_emballage_arrivé,"[carton, abîmé, emballage, arrivé, colis, ouve...","[carton très abîmé , marchandise pas détérioré..."
3,2,221,2_articles_article_articles conformes_très,"[articles, article, articles conformes, très, ...","[les articles sont bien !, articles conforment..."
4,3,154,3_qualité_déçue qualité_produits_déçu,"[qualité, déçue qualité, produits, déçu, déçue...",[très déçu par la qualité du produit . qualité...
...,...,...,...,...,...
56,55,14,55_qualite_sinon rien_semelles_vernis,"[qualite, sinon rien, semelles, vernis, plate,...","[dommage pour la veste en jean , sinon rien à ..."
57,56,12,56_protégé_livrée_endroit_vaisselle,"[protégé, livrée, endroit, vaisselle, origine,...","[j'ai commandé un service vaisselle , tout est..."
58,57,11,57_lampe_pied_vendue_boites,"[lampe, pied, vendue, boites, accessoires, pri...",[lampe qui n'est pas montable entièrement car ...
59,58,10,58_bla_bla bla_bouteille_entre,"[bla, bla bla, bouteille, entre, achat, bon, p...",[j ’ ai commandé début décembre 2016 2 taboure...
60,59,10,59_panier_dont_code_découvrir,"[panier, dont, code, découvrir, clients, servi...","[service client déplorable , offre répétitive ..."

In [28]:
# Mots-clés associés à un topic
models["français"].get_topic(0)

[('commande', np.float64(0.025884285984158574)),
 ('livraison', np.float64(0.025211979046278556)),
 ('très', np.float64(0.024817338316522306)),
 ('plus', np.float64(0.020921395958509892)),
 ('colis', np.float64(0.018338502160680822)),
 ('bien', np.float64(0.018071155498876515)),
 ('service', np.float64(0.01718369697262888)),
 ('site', np.float64(0.016815205010169126)),
 ('qualité', np.float64(0.01647076409897316)),
 ('tout', np.float64(0.015404110809493402))]

In [29]:
# Mots-clés associés à un topic
models["multilingue"].get_topic(0)

[('commande', np.float64(0.01334156410495559)),
 ('livraison', np.float64(0.012767621325075182)),
 ('très', np.float64(0.011153080393126093)),
 ('plus', np.float64(0.010639825498328792)),
 ('service', np.float64(0.009334400229026532)),
 ('colis', np.float64(0.008835134628431855)),
 ('bien', np.float64(0.00879317252851676)),
 ('client', np.float64(0.008724232335621123)),
 ('site', np.float64(0.008699768087124105)),
 ('rien', np.float64(0.008514388082079043))]

In [30]:
fig1 = models["français"].visualize_topics(top_n_topics=10)
fig2 = models["multilingue"].visualize_topics(top_n_topics=10)

combined_fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=("Modèle 1 : Français", "Modèle 2 : Multilingue")
)

for trace in fig1['data']:
    combined_fig.add_trace(trace, row=1, col=1)

for trace in fig2['data']:
    combined_fig.add_trace(trace, row=1, col=2)

combined_fig.update_layout(
    title_text="Répartition des topics",
    showlegend=False,
    height=600,
    width=1000
)

combined_fig.show()

In [31]:
models["français"].visualize_barchart(top_n_topics=10)

In [32]:
models["multilingue"].visualize_barchart(top_n_topics=10)

In [33]:
models["multilingue"].visualize_hierarchy()

In [34]:
models["multilingue"].visualize_hierarchy()