### Chargement du DataFrame

In [40]:
import pandas as pd

df = pd.read_csv("../data/processed/dataset_avis.csv")

df.head()

,comment_id,Commentaire,star,date,client,reponse,source,company,ville,maj,date_commande,ecart,clean_comment,qualité produit,service livraison,service client
0,2,"Vente Lacoste Honteuse , article erroné , arti...",1,2021-06-19 00:00:00+00:00,Vanessa L,NaN,TrustPilot,ShowRoom,NaN,NaN,NaN,NaN,"vente lacoste honteuse , article erroné , arti...",1,0,0
1,6,Annulation de commande après 2 mois d ’ attent...,1,2021-06-18 00:00:00+00:00,aurore regnier,"Bonjour Aurore , Je suis sincèrement désolé d'...",TrustPilot,ShowRoom,NaN,NaN,NaN,NaN,annulation de commande après 2 mois d ’ attent...,0,0,1
2,8,Extrêmement deçu pour mes achats lors la vente...,1,2021-06-18 00:00:00+00:00,Ayna,NaN,TrustPilot,ShowRoom,NaN,NaN,NaN,NaN,extrêmement deçu pour mes achats lors la vente...,1,0,0
3,9,S'il y'avait une option : ne pas mettre d'étoi...,1,2021-06-18 00:00:00+00:00,linda Ng,NaN,TrustPilot,ShowRoom,NaN,NaN,NaN,NaN,s'il y'avait une option : ne pas mettre d'étoi...,1,0,0
4,10,ARNAQUE J ’ ai acheté une combinaison blanche ...,1,2021-06-18 00:00:00+00:00,Sarah,NaN,TrustPilot,ShowRoom,NaN,NaN,NaN,NaN,arnaque j ’ ai acheté une combinaison blanche ...,1,0,0

### Distribution des classes

In [ ]:
labels = ["qualité produit", "service livraison", "service client"]

class_distribution = df[labels].sum().to_frame(name="nb_commentaires")
class_distribution["pourcentage"] = (
    class_distribution["nb_commentaires"] / len(df) * 100
)

class_distribution

                   nb_commentaires  pourcentage
qualité produit               3669    56.143841
service livraison             2730    41.775057
service client                1009    15.439939

### Affichage d'avis au hasard

In [48]:
labels = [
    "qualité produit",
    "service livraison",
    "service client"
]

samples = []

pd.set_option("display.max_colwidth", None)

df = df.drop(columns=["client"], errors="ignore")

for label in labels:
    sample_df = df[df[label] == 1].sample(
        n=3,
        random_state=None  # aléatoire à chaque exécution
    )
    
    sample_df = sample_df.copy()
    sample_df["label_cible"] = label  # pour savoir pourquoi il est sélectionné
    
    samples.append(sample_df)

result = pd.concat(samples)

display_cols = result.rename(columns={
    "qualité produit": "produit",
    "service livraison": "livraison",
    "service client": "client"
})

display_cols = display_cols[[
    "label_cible",
    "produit",
    "livraison",
    "client",
    "clean_comment"
]]

display(display_cols)

# for _, row in display_cols.iterrows():
#     print("─" * 100)
#     print(f"Label cible : {row['label_cible']}")
#     print(f"Produit    : {row['produit']}")
#     print(f"Livraison  : {row['livraison']}")
#     print(f"Client    : {row['client']}")
#     print("\nCommentaire :")
#     print(row["clean_comment"])

,label_cible,produit,livraison,client,clean_comment
6329,qualité produit,1,0,0,"vente privée où l'arnaque des frais de livraison.6,50 de frais de livraison pour seulement trois pauvres vêtements , je trouve cela très abusé.de plus , si l'on souhaite effectuer un retour pour articles trop petits ou non conforme , on nous `` vole '' encore de 6,90 de frais de livraison . de la grosse arnaque , faites attention !"
4882,qualité produit,1,0,0,malgré ma pointure la paire de chaussure est trop petite
578,qualité produit,1,0,0,"cliente depuis des années de showroomprivé mais je ne le recommande plus . les articles sont souvent défectueux . je ne sais pas combien de fois j'ai du retourner les articles ( vêtements défectueux , lacets cassé ou perdu l'élasticité , téléphone ne fonctionne pas .. etc ) . la dernière commande était scandaleuse . il s'agit d'un iphone reconditionné que j'ai commandé depuis le 2 juin , et il n'est jamais arrivé alors que le colis est signé livré ... showroomprive nous a demandé plusieurs démarches même la plainte signé à la police ( qui nous a prix énormément de temps ) , je les ai effectué sagement et je les leur ai fourni depuis 10 jours . comme leur délai est très important , je suis allée demander une enquête à la poste . j'ai fourni les résultats de la poste au showroomprive comme quoi le colis est confirmé `` perdu '' . mais showromprivé ne voulait pas nous rembourser et nous a demandé de patienter alors que nous sommes 2 mois de l'achat . dans cette situation difficile collectivement , je trouve qu'ils ne sont pas corrects . a éviter absolument ."
273,service livraison,1,1,0,"une honte ! ! ! ! ! commande ( tennis nike ) reçu début décembre pour offir à noël pour mon fils . lorsqu'il les a essayé la taille n'étais pas bonne du tout , le 40 reçu , correcpond à un 37,5 ou 38 . il n ' a jamais eu de problème de pointure chez de `` vraie '' tennis nike . les tennis reçu sont très mal faites , il y a des traces de colle sur la semelle , elles ne sont pas belles du tout ! ! ! ! ! hélas pour moi le delais pour renvoyer les chaussures est dépassé de 5 jours . le service client m'atteste que ce sont bien `` des vraies tennis '' et que les chaussures ont bien etaient envoyés par nike . après vérification c'est faux ! ! ! ! bref après avoir était cliente depuis plus de 10ans c'est terminé pour moi les commandes chez eux et je vous conseille d'en faire autant ! ! ! ! !"
1248,service livraison,0,1,0,"livraison plus rapide qu ’ annoncée , emballage soigné . juste dommage qu ’ on doive payer les frais de retour en cas de renvoi d ’ articles trop petits !"
2188,service livraison,0,1,0,la commande est arrivée à un point colis différent de celui demandé et difficilement accessibles .
2995,service client,0,0,1,"très bien coupé , jolie matière et taille juste . belle surprise"
5329,service client,1,0,1,"l'expérience re-turn est une catastrophe : retour d'un article dont j'attends le crédit sur le porte-monnaie depuis 15 jours ! toujours à o€ ( en dépit d'un mail m'annonçant que le montant a été crédité ! ) . a priori je ne suis pas prête d'être remboursée ( vu les expériences des internautes ) ! après plusieurs contacts du service client ( plutôt compréhensif ce faisant ) , le dossier est entre les mains d'un responsable sensé me contacter sous 48 heures ... et ce depuis plus d'une semaine : aucun appel , aucun contact , aucun mail ! résultat : cet article a donc été vendu ( payé ) 2 fois et un des clients attend toujours son remboursement : qui est le grand gagnant dans cette histoire ? c'est ça le concept d'une économie durable et responsable ? ? : ) un conseil : renvoyer vos articles a veepee directement et dans les temps pour vous faire rembourser , c ’ est plus sur ( même si c'est toujours un peu long à mon goût ... et payant , hélas ) ! mais n'oubliez pas que si vous payez avec paypal vous pouvez vous faire rembourser les frais de retour ; )"
70,service client,1,1,1,"des escrocs , une honte.je passe une commande pour une marque de vêtements d'enfants . je sélectionne 10 articles , les frais de livraison s'élèvent à 6.99e à un point relais d'une distance de 40min aller de mon domicile . je suis un peu déçue mais je passe quand même commande car pour le nombre d'articles même si ce n'est pas à côté ça vaut le coup . forcément il faut attendre un mois avant la livraison de la commande . une fois la commande arrivée au point relais je reçois un mail de confirmation . je m ' y rend donc récupérer celle ci . arrivée la bas je constate avec le commerçant du point relais que le colis en question paraît petit et léger pour 10 articles , il vérifie qu'il n ' y a pas de second colis . mais malheureusement ce n'est pas le cas . je lui dis donc ouvrir le colis devant lui pour avoir un témoin du problème s'il s'avère manquer des articles . j'ouvre et la stupéfaction , 2 articles sur 10 . je vérifie sur mon compte la commande pour voir si le manque d'articles avaient été signalé et que je ne l'ai pas remarqué , mais nn rien de cela . je téléphone au service , un monsieur incompétent , impossible pour lui de m'informer sur la raison de ce problème . je rappel 2h après avoir reçu un mail qui me dit que je ne recevrais pas mes articles manquants car la vente est terminée ( forcement un mois que j'ai commandé ) . en rappelant même constatation , un incompétent de plus , je demande un responsable on m'informe qu'il me rappelera sous 24h maximum . 26h passée toujours pas de rappel , je les contacte donc à nouveau . cette fois ci je demande auprès du responsable qui devait me recontacter , mais le monsieur qui me répond fais mine d'être compréhensif et me dit qu'en effet ce n'est pas normal et que le service logistique ne les a pas informé de la rupture de ces 8 produits manquants , donc il me dit que je vais sûrement pouvoir les recevoir après enquête pour savoir où ils ont pu passé . je préfère lui faire confiance , envoi l'attestation sur l'honneur de non réception de ces produits dans l'heure pour que l'enquête puisse avancer . puis le soir même à 23h30 veille de jour férié je reçois un mail du service m'informant que malgré tous leurs efforts ils ne pourront m'envoyer mes articles et qu'un remboursement est déjà parti et se fera sous 5 jours . mais bien sûr le montant du remboursement ne contient pas les 6.99e de livraison . et je n'ai aucune remise pour compenser mon aller retour d'une heure 20 pour y trouver 2 articles . bref je n'ai eu aucune économie sur ces 2 articles en y rajoutant les frais de livraison et ceux de transport . si j'avais su je n'aurais pas commander du tout . et cela m'aurait éviter de me retrouver les mains vides pour les cadeaux de naissance à venir .. il faut savoir que c'est une marque qui est assez chère de base et que même avec remise les articles ne sont pas vendu 5 euros . ma commande avait quand même un certain coût . je ne compte pas en rester là ! c'est inadmissible.je précise que j'avais déjà eu 2 petits soucis avec showroom avant celui ci mais la c'est juste le pompon ! ! c'est terminé je ne passerais plus jamais de commande via ce site . escrocs ! !"

### Création des variables X_test/y

In [20]:
X_text = df["clean_comment"].values
y = df[[
    "qualité produit",
    "service livraison",
    "service client"
]].values

### Encoding de X_text

In [21]:
from sentence_transformers import SentenceTransformer

model_emb = SentenceTransformer(
    "dangvantuan/french-document-embedding",
    trust_remote_code=True
)

X_embeddings = model_emb.encode(
    X_text,
    batch_size=32,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

Batches:   0%|          | 0/205 [00:00<?, ?it/s]

### Séparation des données en train/test

In [55]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_embeddings,
    y,
    test_size=0.2,
    random_state=42
)

### Création du modèle

In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier

log_reg = LogisticRegression(
    penalty="l2",
    solver="lbfgs",
    max_iter=1000,
    class_weight="balanced"
)

clf = OneVsRestClassifier(log_reg)

### CrossVal

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer, f1_score

scorer = make_scorer(f1_score, average="micro")

cv_scores = cross_val_score(
    clf,
    X_embeddings,
    y,
    cv=5,
    scoring=scorer,
    n_jobs=-1
)

print("F1 micro par fold :", cv_scores)
print("F1 micro moyen   :", cv_scores.mean())
print("Écart-type       :", cv_scores.std())

# la validation croisée met en évidence l'instabilité du modèle (ecart-type élevé : 0.078)

F1 micro par fold : [0.62644488 0.78401122 0.77442024 0.77264716 0.609076  ]
F1 micro moyen   : 0.7133199004873024
Écart-type       : 0.07831257621337577

### Entrainement du modèle et calcul des probas

In [ ]:
clf.fit(X_train, y_train)

In [ ]:
y_proba = clf.predict_proba(X_test)

### Affichage des résultats

In [61]:
from sklearn.metrics import classification_report

threshold = 0.5

y_pred = (y_proba >= threshold).astype(int)

print(classification_report(
    y_test,
    y_pred,
    target_names=[
        "qualité produit",
        "service livraison",
        "service client"
    ]
))

                   precision    recall  f1-score   support

  qualité produit       0.79      0.79      0.79       717
service livraison       0.73      0.74      0.74       547
   service client       0.41      0.78      0.53       209

        micro avg       0.68      0.77      0.72      1473
        macro avg       0.64      0.77      0.69      1473
     weighted avg       0.72      0.77      0.74      1473
      samples avg       0.72      0.79      0.73      1473

c:\IA\trustpilot\venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [62]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test, y_pred, average=None)
for label, score in zip(
    ["qualité produit", "service livraison", "service client"], f1
):
    print(label, score)

qualité produit 0.7921896792189679
service livraison 0.7368421052631579
service client 0.5346534653465347

In [63]:
import numpy as np

labels = ["qualité produit", "service livraison", "service client"]

threshold = 0.5

thresholds = {
    "qualité produit": threshold,
    "service livraison": threshold,
    "service client": threshold
}

y_pred = np.zeros_like(y_proba, dtype=int)

for i, label in enumerate(labels):
    y_pred[:, i] = (y_proba[:, i] >= thresholds[label]).astype(int)

from sklearn.metrics import confusion_matrix

for i, label in enumerate(labels):
    tn, fp, fn, tp = confusion_matrix(
        y_test[:, i],
        y_pred[:, i]
    ).ravel()
    
    df_cm = pd.DataFrame(
        [[tn, fp], [fn, tp]],
        index=["Vrai 0", "Vrai 1"],
        columns=["Prédit 0", "Prédit 1"]
    )
    
    print(f"\n{label}")
    display(df_cm)

qualité produit

        Prédit 0  Prédit 1
Vrai 0       441       149
Vrai 1       149       568

service livraison

        Prédit 0  Prédit 1
Vrai 0       611       149
Vrai 1       141       406

service client

        Prédit 0  Prédit 1
Vrai 0       863       235
Vrai 1        47       162